### ISSUE TITLE
Possible to use Github App instead of oAuth app for Github VCS

### ISSUE THREAD

**Issue by stanleyz** [AzBuilder/terrakube#1070]
### Feature description 💡

Github app is better in integration with services because it can act as an independent user, meaning it doesn't tie to any particular account requiring additional management.

**Comment by alfespa17** [comment]
I guess adding an option so you can select if you want to use a Github App or Github Oauth when you are creating the VCS connection will work, but I am not sure about the implication or the refactor need it for this change.

If anyone would like to help with this issue all pull request are welcome.

**Comment by stanleyz** [comment]
I can take a look,  I will likely split the implementation into two (or even three, with one for executor, one for registry) parts with the backend in first.

Because the JWT token can only live less than 10 minutes, I am thinking of passing `client id` and `private key` in the job to the executor and generating the JWT token when needed. Within the executor, instead of passing `vcstype` and `access_token` around different methods in classes, I'll just pass in `TerraformJob`, similarly `VcsAttributes` for the registry.

https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/generating-a-json-web-token-jwt-for-a-github-app

For the database record, will use `client_secret` as the place for `private key` and re-purpose the `access_token` to a fixed value named `JWT` for Github App access.

What do you think? any comments?

**Comment by alfespa17** [comment]
I had a similar issue when implementing the token logic for gitlab, bitbucket and azure devops because the token was only valid for some specific period of time as you can see here:

https://github.com/AzBuilder/terrakube/blob/3f2c77312b96e0b88e7d7599391756fd79ac02b0/api/src/main/java/org/terrakube/api/plugin/vcs/TokenService.java#L66

https://github.com/AzBuilder/terrakube/blob/3f2c77312b96e0b88e7d7599391756fd79ac02b0/api/src/main/java/org/terrakube/api/plugin/vcs/TokenService.java#L75

https://github.com/AzBuilder/terrakube/blob/3f2c77312b96e0b88e7d7599391756fd79ac02b0/api/src/main/java/org/terrakube/api/plugin/vcs/TokenService.java#L84

What I did wast to add a quartz job that takes care to renew the token automatically and I didn't have to worry about that anymore:

https://github.com/AzBuilder/terrakube/blob/3f2c77312b96e0b88e7d7599391756fd79ac02b0/api/src/main/java/org/terrakube/api/plugin/scheduler/ScheduleVcs.java#L52

I guess you can pass the data to the executor to authenticate and that should work, but for the registry will be a little different because the registry access the token from the API using the `internal token authentication`

https://github.com/AzBuilder/terrakube/blob/3f2c77312b96e0b88e7d7599391756fd79ac02b0/api/src/main/java/org/terrakube/api/rs/vcs/Vcs.java#L65

https://github.com/AzBuilder/terrakube/blob/3f2c77312b96e0b88e7d7599391756fd79ac02b0/registry/src/main/java/org/terrakube/registry/service/module/ModuleServiceImpl.java#L54

https://github.com/AzBuilder/terrakube/blob/3f2c77312b96e0b88e7d7599391756fd79ac02b0/registry/src/main/java/org/terrakube/registry/service/module/ModuleServiceImpl.java#L56

**Comment by stanleyz** [comment]
Thanks @alfespa17 , that's good info. Since you've gotten the workflow for the other providers, I'd follow the existing pattern. 

But refreshing the token every 10 minutes sounds a bit too frequent, it makes sense in a busy system. Saying that however I don't have a better solution, especially with the frequency the registry needs to refresh the managed modules.

**Comment by alfespa17** [comment]
> I have found this issue after trying to use the Github apps for the VCS. So, I assume that at this moment oAuth apps are the only option?

That is correct, right now only oauth apps are supported
