### ISSUE TITLE
Docker compose fails due to CORs

### ISSUE THREAD

**Issue by xorima** [AzBuilder/terrakube#1128]
### Bug description 🐞

When using docker compose CORS failures are happening if you try to create a new organisation

### Steps to reproduce

# Terrakube Docker Compose

## Local DNS entries

Update the /etc/hosts file adding the following entries:

```bash
127.0.0.1 terrakube-api
127.0.0.1 terrakube-ui
127.0.0.1 terrakube-executor
127.0.0.1 terrakube-dex
127.0.0.1 terrakube-registry
```

## Running Terrakube Locally.

```bash
git clone https://github.com/AzBuilder/terrakube.git
cd terrakube/docker-compose
docker-compose up -d
```

Terrakube will be available in the following URL:

* http://terrakube-ui:3000
  * Username: admin@example.com
  * Password: admin 

Login to web ui, click create organisation, it will fail to create due to CORs error 

### Expected behavior

Works without issue

**Comment by alfespa17** [comment]
For me it is working.

![image](https://github.com/user-attachments/assets/edb3de6b-3c33-4320-ab24-c519c0a33c46)

**Comment by alfespa17** [comment]
By the way using docker-compose can help to quickly test some of the features but not all are available because some parts require https.

If you want to test all the features with docker-compose you can check this discussion.

https://gist.github.com/SolomonHD/b55be40146b7a53b8f26fe244f5be52e

Or you can use minikube like we explained here:

https://docs.terrakube.io/getting-started/deployment/minikube-+-https
