### ISSUE TITLE
Waiting for -36 queued run(s) to finish before starting...

### ISSUE THREAD

**Issue by stanleyz** [AzBuilder/terrakube#1285]
### Bug description 🐞

The message printed from the local terraform run about queues is wrong.

### Steps to reproduce

Have multiple workspaces, multiple runs at the same time, and 10 jobs waiting for approval in the history

**Comment by alfespa17** [comment]
That message under some circumstances will be wrong because terrakube manage queue at the workspace level and there is some code in the terraform cli that checks the queue at the organization level in this function:

https://github.com/hashicorp/terraform/blob/2770cb376c53a9ef6ea63482d7eaf83c0bfe887e/internal/cloud/backend_common.go#L48

If I remember correctly in this part of the code:

https://github.com/hashicorp/terraform/blob/2770cb376c53a9ef6ea63482d7eaf83c0bfe887e/internal/cloud/backend_common.go#L173

https://github.com/hashicorp/terraform/blob/2770cb376c53a9ef6ea63482d7eaf83c0bfe887e/internal/cloud/backend_common.go#L196

Some months ago, I implemented the logic in these methods, I guess that could be improve:

https://github.com/AzBuilder/terrakube/blob/9b45945f3e9a2b509a91b440052831af330519ba/api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeService.java#L188

https://github.com/AzBuilder/terrakube/blob/9b45945f3e9a2b509a91b440052831af330519ba/api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeService.java#L954

**Comment by alfespa17** [comment]
That message is related to this pull request.

https://github.com/AzBuilder/terrakube/pull/983

**Comment by stanleyz** [comment]
Thanks, should have talked with you first, it took me some time to find the source code and understand what's going on.
