### ISSUE TITLE
Upgrade junit-jupiter-api.version from 5.10.3 to 5.11.2

### ISSUE THREAD

**Issue by alfespa17** [AzBuilder/terrakube#1429]
### Feature description 💡

Fix issues when using a newer junit jupiter library. The build is always failing when updating the library

### Anything else?

Example:

https://github.com/AzBuilder/terrakube/pull/1385

**Comment by dawidmalina** [comment]
The problem here is not related to version change that introduced breaking change. The problem here is that we are managing `org.junit.jupiter:junit-jupiter-api` and `org.junit.jupiter:junit-jupiter-engine` explicitly and we ended up with conflict with `org.springframework.boot:spring-boot-starter-test` that come with it's own versioning schema.

In other words we were trying to use `5.11.2` while `org.springframework.boot:spring-boot-starter-test:jar:3.3.4` depends on version `5.10.3`.

Simplest solution here would be to remove explicit versioning of jupiter and use the version managed by spring.

I can drop a PR if you want.

**Comment by alfespa17** [comment]
> The problem here is not related to version change that introduced breaking change. The problem here is that we are managing `org.junit.jupiter:junit-jupiter-api` and `org.junit.jupiter:junit-jupiter-engine` explicitly and we ended up with conflict with `org.springframework.boot:spring-boot-starter-test` that come with it's own versioning schema.
> 
> In other words we were trying to use `5.11.2` while `org.springframework.boot:spring-boot-starter-test:jar:3.3.4` depends on version `5.10.3`.
> 
> Simplest solution here would be to remove explicit versioning of jupiter and use the version managed by spring.
> 
> I can drop a PR if you want.

Feel free to create the PR, all help is welcome
