### ISSUE TITLE
Terrakube on docker-compose

### ISSUE THREAD

**Issue by sumanthkulkarni13** [AzBuilder/terrakube#423]
### Bug description 🐞

Im trying to run docker-compose based Terrakube on a virtualbox backed by vagrant

Whole stack is up and running fine without any issues whatsoever. 

However the Login UI landing page doesn't appear to be fully loaded and doesn't show up username/password fields

![Terrakube-Login](https://github.com/AzBuilder/terrakube/assets/17407870/dea1859c-aa88-47b8-a29e-8618907a1f57)

Have followed the instructions in the docker-compose page : https://docs.terrakube.io/getting-started/docker-compose

Containers in the entire stack are up and running fine:
![docker-ps](https://github.com/AzBuilder/terrakube/assets/17407870/ab1ffcda-c556-435d-b429-22ea34cb7c5e)

Local DNS entries have been added
`[vagrant@localhost docker-compose]$ cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
127.0.0.1 terrakube-api
127.0.0.1 terrakube-ui
127.0.0.1 terrakube-executor
127.0.0.1 terrakube-dex
127.0.0.1 terrakube-registry`

No other visible errors whatsoever. Have spot checked each container for errors. Selinux has been disabled. Abundant memory available for the processes to run. 

### Steps to reproduce

Download the Docker compose file and start the stack

`git clone https://github.com/AzBuilder/terrakube.git
cd terrakube/docker-compose
docker-compose up -d`

### Expected behavior

Terrakube UI must function as expected with login fields

**Comment by alfespa17** [comment]
Hello @sumanthkulkarni13 

Please check [this](https://docs.terrakube.io/getting-started/docker-compose).

It should work if you login using the following URL
```
http://terrakube-ui:3000
- Username: admin@example.com
- Password: admin
```

**Comment by sumanthkulkarni13** [comment]
Sorry @alfespa17 no dice.
![docker-ps](https://github.com/AzBuilder/terrakube/assets/17407870/4ca64017-a719-4cc2-a22e-da78c88d7782)

**Comment by alfespa17** [comment]
It should work

![image](https://github.com/AzBuilder/terrakube/assets/4461895/3827c645-3fd5-4465-8a32-b3d18e1333d9)

![image](https://github.com/AzBuilder/terrakube/assets/4461895/45009933-0c12-49db-9054-f574262017f8)

![image](https://github.com/AzBuilder/terrakube/assets/4461895/b1ce75d7-194e-4fda-a528-784161054656)

**Comment by sumanthkulkarni13** [comment]
My bad, the login flow redirects to dex URL, should have added the resolver on the host. Pls consider this closed.

**Comment by SolomonHD** [comment]
> My bad, the login flow redirects to dex URL, should have added the resolver on the host. Pls consider this closed.

Hey I'm seeing this same issue, I'm trying to put everything behind traefik, you fixed this just by adding to /etc/hosts file on the host?

**Comment by alfespa17** [comment]
Hello @SolomonHD 

Make sure you edit your /etc/hosts file with

```
127.0.0.1 terrakube-api
127.0.0.1 terrakube-ui
127.0.0.1 terrakube-executor
127.0.0.1 terrakube-dex
127.0.0.1 terrakube-registry
```

It should work

**Comment by SolomonHD** [comment]
I've made progress. I have heavily modified the docker compose file because I want to run the stack behind a reverse proxy called traefik. 

Solved Problems:
1) Login button does nothing: caused by mixing HTTPS/HTTP, I had the ui URL as HTTPS--HTTPS decrypts on traefik, container gets HTTP-- and dex as http and that is not allowed. Fixed after I changed dex to a URL with HTTPS, but that led to problem 2
2) CORS, the login button would not work because it needed the Allow Origin header on the dex URL.  I added this to my traefik labels: 
```
  traefik.http.middlewares.terrakube-dex-allow-origin.headers.accesscontrolallowmethods: GET,OPTIONS,PUT
  traefik.http.middlewares.terrakube-dex-allow-origin.headers.accesscontrolallowheaders: "*"
  traefik.http.middlewares.terrakube-dex-allow-origin.headers.accesscontrolalloworiginlist: >
    https://${ENV_PREFIX:-}terrakube.int.emory.edu,https://${ENV_PREFIX:-}tk.int.emory.edu
  traefik.http.middlewares.terrakube-dex-allow-origin.headers.accesscontrolmaxage: 100
  traefik.http.middlewares.terrakube-dex-allow-origin.headers.addvaryheader: true
```
After redeploying I could login :D, but that leads to problem 3 

3) API and UI cannot talk. I can login to the UI but I cannot create an org or token. The api container has this message:
```
java.lang.IllegalArgumentException: Unable to resolve the Configuration with the provided Issuer of "https://dev-vw.int.emory.edu/dex"
...
java.lang.IllegalArgumentException: Unable to resolve the Configuration with the provided Issuer of "https://dev-vw.int.emory.edu/dex"
```
dev-vw.int.emory.edu is the URL for the dex container, dev-tk is for the API container.
I don't know exactly why it's timing out, I believe I've changed the issuer in all relevant spots, and I added 127.0.0.1 in the /etc/hosts file for all the URLs I've added.

**Comment by alfespa17** [comment]
I think the issue is that inside the API container the dev-vw.int.emory.edu this hostname does not exist if you pay attention inside the docker compose the API is able to resolve DEX because it is using the same docker network 

Api en variables 
https://github.com/AzBuilder/terrakube/blob/main/docker-compose/api.env#L13

Docker compose.
https://github.com/AzBuilder/terrakube/blob/main/docker-compose/docker-compose.yaml#L31

That is why when you run the docker compose api can resolve the dex IP inside the container and from outside the container you have modified you local host file to add the IP

I hope this can help you
