### ISSUE TITLE
Keep getting 'unsupported attribute' errors on state migration

### ISSUE THREAD

**Issue by jderieg** [AzBuilder/terrakube#594]
### Bug description 🐞

Hi guys, I'm attempting to run some state migrations from terrakube.io to our Terrakube instance. I keep getting 'unsupported attribute' errors on various states. The attribute that it errors out on isn't always the same, but it happens when there is an attribute in the state file that is set to 'null'. For example:

![2023-11-13_13-28](https://github.com/AzBuilder/terrakube/assets/63372114/909e3da1-ef22-493e-aea3-5b0f9016bdf6)

And this is the error:
![2023-11-13_13-30](https://github.com/AzBuilder/terrakube/assets/63372114/2617fc5f-e883-4c7b-aa5a-60706d850aea)

### Steps to reproduce

Try to migrate any state file that has an attribute with a null value and it will throw that error.

### Expected behavior

Ignore the null attribute

**Comment by alfespa17** [comment]
Hello @jderieg 

I am not really sure about this issue because internally we are not doing any kind of processing or modification to the terraform state when using the CLI driven workflow, the terraform CLI is just sending a base64 encoded string to Terrakube  API and we take the value and save it.

Do you see any logs in the API?

Could you share some terraform code that generate a state with a null value?

Maybe it is a terraform CLI or terraform provider issue but not sure....

**Comment by jderieg** [comment]
OK, so I did some more testing.
If I completely delete my local .terraform directory and .terraform.lock.hcl file, do a new 'terraform init' and pull a brand-new fresh state file from the source, it pushes up to Terrakube without error. I'm not exactly sure why though. 
I think it's possible that my local .terraform directory had existed for long enough that some state changes had nullified some of the attribute values that existed, so Terraform didn't know what to do with them on the state push. That's my best guess.
Anyway, I guess the workaround is to delete the local .terraform directory and re-init.
I didn't see anything else in the api log when it threw this error, so maybe it didn't even get that far and the error was thrown by my local Terraform binary.
I think we can close this issue as it doesn't actually seem to be related to Terrakube. Thanks!
