### ISSUE TITLE
Migrate Registry to Golang

### ISSUE THREAD

**Issue by jcanizalez** [AzBuilder/terrakube#660]
### Feature description 💡

Move the registry from java to Golang.

steps:
- [ ] Create a new folder in the repo registry-go
- [ ] Migrate all the logic from java to golang
- [ ] Create a new image azbuilder/registry
- [ ]  Mantain the new image in preview mode for at least 3 minor versions. During this time both java and go registry can be used alternative.
- [ ] Once all tests are completed, delete the registry (java) and rename registry-go to registry. 
- [ ] Replace the reference in docker-compose and helm chart

### Anything else?

Once v3 it's released the new registry should be run as a single component with the api

**Comment by alfespa17** [comment]
I am closing this one, I think this should belong to a different repository.

**Comment by ilkerispir** [comment]
@alfespa17, @jcanizalez, I'm keen on this issue. If any assistance is needed I would be happy to help.

**Comment by alfespa17** [comment]
> @alfespa17, @jcanizalez, I'm keen on this issue. If any assistance is needed I would be happy to help.

Hello @ilkerispir, I am glad that you are interested in building a compatible registry I really learned a lot about how terraform/tofu registry works when I implemented the terrakube private registry some years ago.

If you would like implement a registry that is compatible with terrakube or even your own custom registry you could star by checking the following docs:

Service discovery:

https://developer.hashicorp.com/terraform/internals/remote-service-discovery

Login protocol:

https://developer.hashicorp.com/terraform/internals/login-protocol

Registry protocol:

https://developer.hashicorp.com/terraform/internals/module-registry-protocol

https://opentofu.org/docs/internals/module-registry-protocol/

In a high level it is just implementing like 4 http endpoints if I remember correctly and expose the service with a valid http certificate.

I always thought this issue should belong to a different GitHub repository because it will basically be an entire code rewrite.

If you would like to create a custom registry I can assure you will learn a lot and if you would like to make it compatible with terrakube I can explain the required API request that you will need.

By the way you can send us a message in the slack workspace that we created recently if you have questions.

**Comment by ilkerispir** [comment]
Hello @alfespa17, 

First of all, thank you very much for the detailed answer.

You haven't started this work yet, have you? I couldn't see any repos regarding this issue.

I also joined your Slack workspace, thank you.

**Comment by alfespa17** [comment]
> Hello @alfespa17,
> 
> First of all, thank you very much for the detailed answer.
> 
> You haven't started this work yet, have you? I couldn't see any repos regarding this issue.
> 
> I also joined your Slack workspace, thank you.

We didn't create any repository, if you would like to do a POC regarding the issue I could create it.

**Comment by ilkerispir** [comment]
> We didn't create any repository, if you would like to do a POC regarding the issue I could create it.

Frankly, it's too early for me right now, I'll have to review the docs you sent.
