### ISSUE TITLE
Terrakube Executor run as Self-Hosted Agent

### ISSUE THREAD

**Issue by iam-take** [AzBuilder/terrakube#718]
### Feedback

We are wondering if it is possible to run the Terrakube executor remotely. We have several environments which do not have line of sight to the current instance of Terrakube. Some of the resources are not public accessible and currently not manageable through Terrakube since the executor is deployed in the same AKS cluster. 

In the documentation we can't find a option for hosting the executor as a Self-Hosted agent  which would connect over the internet to the API server. We might be reading over it but would love to hear the options we currently would have and if this does not exist would be on the roadmap?

**Comment by alfespa17** [comment]
There is an open issue about that feature.

https://github.com/AzBuilder/terrakube/issues/635

One idea is to run a workspace job as a kubernetes job in different container and the other one is having an option to have several "agents" to run remotely and you can select in which agent you you could run the job

**Comment by alfespa17** [comment]
I added support to create a "job agents" in this [PR](https://github.com/AzBuilder/terrakube/pull/770), now you can select in which agent a remote job will be running. I still need to update the helm chart to allow to deploy a single executor but I think is a good start.

**Comment by alfespa17** [comment]
Documentation for this feature was added here

https://docs.terrakube.io/getting-started/deployment/self-hosted-agents

All feedback is welcome

**Comment by iam-take** [comment]
@alfespa17  Thanks for creating this feature, I've tried this but is my assumption correct that this agent is required to be deployed in the same Kubernetes cluster as where the terrakube cluster is deployed in? 

I've tried deploying it in a seperate cluster as we really require it to be hosted seperately from in a seperate tenant / subscription. But we require to set some Redis settings which we currently do not actively configure in the Terrakube configuration. But also suggest that it needs to be deployed in the same cluster.

**Comment by alfespa17** [comment]
Hello @iam-take 

In the documentation I assume that you are using the same cluster.

But In theory you could deploy it in a different cluster but you will have to add some ingress with https to the executor manually because the API send a http request to trigger the job execution and maybe you will have to use some external redis option.

By default when you deploy terrakube it will create a redis deployment inside the namespace using the following (if you check the namespace where you installed terrakube you will see a service called terrakube-redis-master)

https://github.com/AzBuilder/terrakube-helm-chart/blob/0f51e6c547b6bc369a496b4d6dcb25eb864956fc/charts/terrakube/values.yaml#L156

https://github.com/AzBuilder/terrakube-helm-chart/blob/0f51e6c547b6bc369a496b4d6dcb25eb864956fc/charts/terrakube/values.yaml#L174

If you deactivate the default redis deployment and use some external redis configuration I guess it should work for you because the self hosted executor will be able to communicate with the terrakube API and will be able to send the temp information for the log streaming to the external redis

I hope this can help you.
