### ISSUE TITLE
docker-compose TerrakubeHostname incorrect, or incorrectly used by Gitlab VCS

### ISSUE THREAD

**Issue by MatthewJohn** [AzBuilder/terrakube#795]
### Bug description 🐞

The TerrakubeHostname in the docker-compose example is set to `http://terrakube-api:8080`.
However, in the Gitlab VCS, it is treated as a domain (with an optional port):
```
    public GitLabToken getAccessToken(String vcsId, String clientId, String clientSecret, String tempCode, String callback, String endpoint) throws TokenException {
        GitLabToken gitLabToken = getWebClient(endpoint).post().uri(uriBuilder -> uriBuilder.path("/oauth/token")
                        .queryParam("client_id", clientId)
                        .queryParam("client_secret", clientSecret)
                        .queryParam("code",tempCode)
                        .queryParam("grant_type", "authorization_code")
                        .queryParam("redirect_uri", String.format("https://%s/callback/v1/vcs/%s", hostname, callback == null ? vcsId: callback))
                        .build())
```

This has two issues:
 * Using the docker-compose example (using http) makes testing the Gitlab VCS impossible (because https is hard-coded in the Gitlab VCS code)
 * It is unclear as to whether TerrakubeHostname  _should_ include a protocol, either the docker-compose incorrect contains the protocol OR the Gitlab VCS code is incorrectly prepending the protocol

### Steps to reproduce

Use the docker-compose example:
```
cd docker-compose
docker-compose up
```
Setup VCS integration with gitlab (tested with self-hosted enterprise).
Use "Connect to gitlab".
Error is thrown due to error 400 from gitlab, due to the token URL containing:
```
https://gitlab.example.com/oauth/token?client_id=something&client_secret=somethingelse&code=acode&grant_type=authorization_code&redirect_uri=https://http://terrakube-api:8080/callback/v1/vcs/some-uuid-4
```

### Expected behavior

Either:
 * "Connect to gitlab" works as expected in example, respecting either http/https URL for TerrakubHostname, or
 * VCS integration is disabled when using http

**Comment by alfespa17** [comment]
You can use the docker compose to quickly test terrakube but some features won't be available like the terraform login and registry protocol, if you are testing I would suggest using the following:

https://docs.terrakube.io/getting-started/deployment/minikube-+-https

If you want to use docker compose some days ago one community member wrote this amazing gist that show how to do the setup using https that enable all the features

https://gist.github.com/SolomonHD/b55be40146b7a53b8f26fe244f5be52e

I think using those two options will be better to test the VCS connections and simplify your testing because you will be using https using some self signed certificates

**Comment by alfespa17** [comment]
We fixed the example in the main branch
